#!/bin/bash

# Path absolut ke virtual environment
VENV_PATH="/root/user/restore-web/myenv"
# Path absolut ke aplikasi
APP_PATH="/root/user/restore-web/app.py"
# Menjalankan aplikasi menggunakan Python dari virtual environment dan mengalihkan output
$VENV_PATH/bin/python $APP_PATH > /root/user/restore-web/app.log 2>&1 &

current_ip=$(curl -s https://ipinfo.io/ip)
echo -e " - Silahkan Lakukan Restore Melalui Browser -"
echo -e "Akses Di Browser : http://$current_ip:5001"
